import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./styles.css";


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-poppins',
  display: 'swap',
});

export const metadata = {
  title: 'Ridenow Rentals',
  description: 'Rent cars and bikes near you',
};

export default function RootLayout(
  { children }: { children: React.ReactNode }
) {
  return (
    <html lang="en" className={poppins.variable}>
      <body>{children}</body>
    </html>
  );
};


{/* const geistSans = Geist({
          variable: "--font-geist-sans",
        subsets: ["latin"],
});

        const geistMono = Geist_Mono({
          variable: "--font-geist-mono",
        subsets: ["latin"],
});

        export const metadata: Metadata = {
          title: "Create Next App",
        description: "Generated by create next app",
};

        export default function RootLayout({
          children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            {children}
          </body>
        </html>
        );
}*/}
